sudo:              false

language:          python

python:
  - 3.6.6

branches:
  - master

install:
  - pip install -r requirements.txt

before_script:
  - cd code

script:
  - python sos.py
  - python test.py
  - python test_sos.py

before_deploy:
  - cd ..
  - git clone https://github.com/hfagerlund/mkdocs-docskimmer.git
  - cp -r $PWD/mkdocs-docskimmer/mkdocs_docskimmer .
  - cp -r $PWD/mkdocs-docskimmer/mkdocs_docskimmer/. ./docs
  - mkdocs build --verbose --clean

deploy:
  provider:        pages
  skip_cleanup:    true
  github_token:    "$github_token"
  local_dir:       site
  on:
    branch:        master

notifications:
  email:           false

env:
  global:
    secure: W+ZL6Tpx/q5fxc3R8Z9KXEPiZQViVXI2nyqhhki2+heX9+K6FvXablLXKMEBUOJ2wbhDA/2wkOpYXdTrLxo4ugjnB2bx9ePZaZSCEtCVqXj1fMBvSbDLcIVNNE3a6cgDNXoc+odvoAnF0/QgiZbDGmeUufE5FKAa6GgLEKlif7Qv/glTV4nfzc3f5ahyu5T9KACXq8LZ5cqbVL9cLJFezanI91HMWsn/6ANd7CH83H5AKixHN4A5TWvCkOvYS5x6gvOgvPHtqtFzGC0JRwCsNnWPshpNjjeu1Gf5k2/QAj5V9bqmaSBvL9AY6ip4DGcZHTdP7rDRFM5rBiIOh3ZABDZwZXA9Tty2aE8xf163+RraOer6s/S9GEkhRNHbzkGjQ0w7zxJM/gYDXgvgBPm0/nknPC7+a1om/5JQL1lOcg8aqGkHJvQVK3vD6nlXsnlhhgYc/c2jRtY6D8/rXcXKkGhuYg/esUzy6ZOa5mjaVm69X8TzOtNHlVUx5ccyYjNBCFJ1q6Tm5PZsggPZV0ZnJ8idn2rfsAjVf05SDq+75TcZ9s5LUl4CsjAvrAMG2e3wTioIPlb0UU5djkieGT3lrVy2CHfGDtSl4+UUHadAm9uhsQK0TXpkHZ8PL54ehJrboVVevTgxo/ND2V3czuEj/uqbXFOnxsAGXfJ+BnbjSWs=
